//! Generate `packages/javascript/src/palettes.generated.ts` from `measured_palettes::CATALOG`.
//!
//! `packages/javascript/src/palettes.ts` used to hand-duplicate the RGB values for every
//! measured display palette, with a comment admitting they had to be "kept in sync manually"
//! with `measured_palettes.rs`. The Python package avoids this by deriving its constants from
//! the same Rust `CATALOG` via FFI at import time (`palettes.py::_load_measured_palettes`);
//! TypeScript can't do that at import time (WASM init ordering), so this generator produces
//! the equivalent module at *build* time instead, mirroring the generator + `--check` idiom
//! used by `opendisplay-protocol/tools/gen_js_structs.py`.
//!
//! DETERMINISM: `CATALOG` is a fixed `&'static [MeasuredPaletteEntry]` (array order, not a
//! hash map), and every field rendered below comes straight from it -- no timestamps, no
//! absolute paths, no iteration-order hazards. Same `CATALOG` in, byte-identical file out.
//!
//! KEY ORDER: each palette's `colors` object is emitted in `CATALOG` entry's `color_names`
//! order, which is asserted (by `measured_palettes_follow_canonical_color_order` in
//! `measured_palettes.rs`) to match the scheme's canonical firmware order. That order is a
//! wire contract -- object key order becomes palette index -- so it is preserved verbatim,
//! never resorted.
//!
//! Usage:
//!   cargo run --example gen_ts_palettes -- --write    (default; (re)generate and write)
//!   cargo run --example gen_ts_palettes -- --check    (verify committed file matches; exit 1 on drift)
//!   cargo run --example gen_ts_palettes -- --stdout   (print the module; write nothing)

use epaper_dithering_core::measured_palettes::CATALOG;
use epaper_dithering_core::palettes::ColorScheme;
use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::ExitCode;

const REGEN_CMD: &str =
    "cargo run --manifest-path packages/rust/core/Cargo.toml --example gen_ts_palettes -- --write";

/// Map a Rust `ColorScheme` variant to the matching member name of the TypeScript
/// `ColorScheme` enum in `packages/javascript/src/palettes.ts`. Written as an explicit
/// match (rather than a case-conversion algorithm) so a newly added variant fails to
/// compile here until its TS name is deliberately chosen, instead of being silently
/// guessed at.
fn ts_scheme_member(scheme: ColorScheme) -> &'static str {
    match scheme {
        ColorScheme::Mono => "MONO",
        ColorScheme::Bwr => "BWR",
        ColorScheme::Bwy => "BWY",
        ColorScheme::Bwry => "BWRY",
        ColorScheme::Bwgbry => "BWGBRY",
        ColorScheme::Grayscale4 => "GRAYSCALE_4",
        ColorScheme::Grayscale16 => "GRAYSCALE_16",
        ColorScheme::SevenColor => "SEVEN_COLOR",
        ColorScheme::BwgbrySplit => "BWGBRY_SPLIT",
    }
}

fn render() -> String {
    let mut out = String::new();

    out.push_str("// @generated by packages/rust/core/examples/gen_ts_palettes.rs -- DO NOT EDIT BY HAND.\n");
    out.push_str("// Source of truth: packages/rust/core/src/measured_palettes.rs (CATALOG)\n");
    out.push_str(&format!("// Regenerate: {REGEN_CMD}\n"));
    out.push_str(
        "// Drift check (CI): cargo run --manifest-path packages/rust/core/Cargo.toml --example gen_ts_palettes -- --check\n",
    );
    out.push_str("//\n");
    out.push_str("// Measured RGB values for real e-paper displays, mirrored from the Rust CATALOG so\n");
    out.push_str("// TypeScript and Python (which derives its constants from the same CATALOG via FFI at\n");
    out.push_str("// import time) can never silently diverge on a recalibration. Key order within each\n");
    out.push_str("// palette's `colors` object matches CATALOG's `color_names` order exactly -- it is a\n");
    out.push_str("// firmware wire contract (palette index = object key position), not cosmetic.\n");
    out.push_str("//\n");
    out.push_str("// `scheme` is emitted as a plain numeric literal (not `ColorScheme.XXX`) so this file\n");
    out.push_str("// has no import-time dependency on palettes.ts, which re-exports these constants --\n");
    out.push_str("// importing back from palettes.ts here would create a circular ES module and risk a\n");
    out.push_str("// temporal-dead-zone error. The `ColorPalette.scheme` field's declared type is a plain\n");
    out.push_str("// `number` for the same reason; each literal is commented with its enum name.\n");
    out.push('\n');
    out.push_str("import type { ColorPalette } from './types';\n\n");

    for entry in CATALOG {
        let scheme_member = ts_scheme_member(entry.scheme);
        let scheme_value = u8::from(entry.scheme);

        out.push_str(&format!("export const {}: ColorPalette = {{\n", entry.id));
        out.push_str(&format!("  scheme: {scheme_value}, // ColorScheme.{scheme_member}\n"));
        out.push_str("  colors: {\n");
        for (name, rgb) in entry.color_names.iter().zip(entry.palette.colors.iter()) {
            out.push_str(&format!(
                "    {name}: {{ r: {}, g: {}, b: {} }},\n",
                rgb[0], rgb[1], rgb[2]
            ));
        }
        out.push_str("  },\n");
        let accent_name = entry.color_names[entry.palette.accent_idx];
        out.push_str(&format!("  accent: '{accent_name}',\n"));
        out.push_str("};\n\n");
    }

    // Exactly one trailing newline.
    while out.ends_with("\n\n") {
        out.pop();
    }
    out
}

fn output_path() -> PathBuf {
    // CARGO_MANIFEST_DIR is `packages/rust/core`; the generated file lives in the sibling
    // JS package. Only used to locate the file to write/check -- never embedded in its
    // content, so the generated output stays free of absolute paths.
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../javascript/src/palettes.generated.ts")
}

/// Print a minimal line-oriented diff (first divergence + counts) so `--check` failures
/// are actionable without pulling in a diff crate.
fn report_drift(path: &Path, existing: &str, generated: &str) {
    eprintln!("DRIFT: {} does not match `CATALOG` output.", path.display());
    let existing_lines: Vec<&str> = existing.lines().collect();
    let generated_lines: Vec<&str> = generated.lines().collect();
    let first_diff = existing_lines
        .iter()
        .zip(generated_lines.iter())
        .position(|(a, b)| a != b)
        .unwrap_or_else(|| existing_lines.len().min(generated_lines.len()));
    eprintln!("  first differing line: {}", first_diff + 1);
    if let Some(line) = existing_lines.get(first_diff) {
        eprintln!("    committed : {line}");
    } else {
        eprintln!("    committed : <missing>");
    }
    if let Some(line) = generated_lines.get(first_diff) {
        eprintln!("    generated : {line}");
    } else {
        eprintln!("    generated : <missing>");
    }
    eprintln!(
        "  ({} committed lines vs {} generated lines)",
        existing_lines.len(),
        generated_lines.len()
    );
    eprintln!("Regenerate with: {REGEN_CMD}");
}

fn main() -> ExitCode {
    let mode = env::args().nth(1).unwrap_or_else(|| "--write".to_string());
    let generated = render();
    let path = output_path();

    match mode.as_str() {
        "--stdout" => {
            print!("{generated}");
            ExitCode::SUCCESS
        }
        "--check" => match fs::read_to_string(&path) {
            Ok(existing) if existing == generated => {
                println!("OK: {} matches CATALOG ({} palettes)", path.display(), CATALOG.len());
                ExitCode::SUCCESS
            }
            Ok(existing) => {
                report_drift(&path, &existing, &generated);
                ExitCode::FAILURE
            }
            Err(err) => {
                eprintln!("DRIFT: cannot read {}: {err}", path.display());
                eprintln!("Regenerate with: {REGEN_CMD}");
                ExitCode::FAILURE
            }
        },
        "--write" => match fs::write(&path, &generated) {
            Ok(()) => {
                println!("wrote {} ({} palettes)", path.display(), CATALOG.len());
                ExitCode::SUCCESS
            }
            Err(err) => {
                eprintln!("failed to write {}: {err}", path.display());
                ExitCode::FAILURE
            }
        },
        other => {
            eprintln!("unknown mode {other:?} (expected --write, --check, or --stdout)");
            ExitCode::FAILURE
        }
    }
}
