// @generated by packages/rust/core/examples/gen_ts_palettes.rs -- DO NOT EDIT BY HAND.
// Source of truth: packages/rust/core/src/measured_palettes.rs (CATALOG)
// Regenerate: cargo run --manifest-path packages/rust/core/Cargo.toml --example gen_ts_palettes -- --write
// Drift check (CI): cargo run --manifest-path packages/rust/core/Cargo.toml --example gen_ts_palettes -- --check
//
// Measured RGB values for real e-paper displays, mirrored from the Rust CATALOG so
// TypeScript and Python (which derives its constants from the same CATALOG via FFI at
// import time) can never silently diverge on a recalibration. Key order within each
// palette's `colors` object matches CATALOG's `color_names` order exactly -- it is a
// firmware wire contract (palette index = object key position), not cosmetic.
//
// `scheme` is emitted as a plain numeric literal (not `ColorScheme.XXX`) so this file
// has no import-time dependency on palettes.ts, which re-exports these constants --
// importing back from palettes.ts here would create a circular ES module and risk a
// temporal-dead-zone error. The `ColorPalette.scheme` field's declared type is a plain
// `number` for the same reason; each literal is commented with its enum name.

import type { ColorPalette } from './types';

export const SPECTRA_7_3_6COLOR: ColorPalette = {
  scheme: 4, // ColorScheme.BWGBRY
  colors: {
    black: { r: 26, g: 13, b: 35 },
    white: { r: 185, g: 202, b: 205 },
    yellow: { r: 202, g: 184, b: 0 },
    red: { r: 121, g: 9, b: 0 },
    blue: { r: 0, g: 69, b: 139 },
    green: { r: 40, g: 82, b: 57 },
  },
  accent: 'red',
};

export const SPECTRA_7_3_6COLOR_V2: ColorPalette = {
  scheme: 4, // ColorScheme.BWGBRY
  colors: {
    black: { r: 31, g: 24, b: 41 },
    white: { r: 168, g: 180, b: 182 },
    yellow: { r: 180, g: 173, b: 0 },
    red: { r: 113, g: 24, b: 19 },
    blue: { r: 36, g: 70, b: 139 },
    green: { r: 50, g: 84, b: 60 },
  },
  accent: 'red',
};

export const MONO_4_26: ColorPalette = {
  scheme: 0, // ColorScheme.MONO
  colors: {
    black: { r: 5, g: 5, b: 5 },
    white: { r: 220, g: 220, b: 220 },
  },
  accent: 'black',
};

export const BWRY_4_2: ColorPalette = {
  scheme: 3, // ColorScheme.BWRY
  colors: {
    black: { r: 5, g: 5, b: 5 },
    white: { r: 200, g: 200, b: 200 },
    yellow: { r: 200, g: 180, b: 0 },
    red: { r: 120, g: 15, b: 5 },
  },
  accent: 'red',
};

export const BWRY_3_97: ColorPalette = {
  scheme: 3, // ColorScheme.BWRY
  colors: {
    black: { r: 10, g: 7, b: 14 },
    white: { r: 173, g: 178, b: 174 },
    yellow: { r: 172, g: 128, b: 0 },
    red: { r: 85, g: 24, b: 14 },
  },
  accent: 'red',
};

export const SOLUM_BWR: ColorPalette = {
  scheme: 1, // ColorScheme.BWR
  colors: {
    black: { r: 5, g: 5, b: 5 },
    white: { r: 200, g: 200, b: 200 },
    red: { r: 120, g: 15, b: 5 },
  },
  accent: 'red',
};

export const HANSHOW_BWR: ColorPalette = {
  scheme: 1, // ColorScheme.BWR
  colors: {
    black: { r: 5, g: 5, b: 5 },
    white: { r: 200, g: 200, b: 200 },
    red: { r: 120, g: 15, b: 5 },
  },
  accent: 'red',
};

export const HANSHOW_BWY: ColorPalette = {
  scheme: 2, // ColorScheme.BWY
  colors: {
    black: { r: 5, g: 5, b: 5 },
    white: { r: 200, g: 200, b: 200 },
    yellow: { r: 200, g: 180, b: 0 },
  },
  accent: 'yellow',
};
